apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: raega829r-go
  janus-idp.io/tekton: raega829r-go
  backstage.io/kubernetes-id: raega829r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: raega829r-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
