apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: raega829r-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: raega829r-go 
  name: raega829r-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: raega829r-go 
